module.exports = {
  WORKOUTS_RECEIVED: "WORKOUTS_RECEIVED",
  WORKOUT_RECEIVED: "WORKOUT_RECEIVED",
  EXERCISES_RECEIVED: "EXERCISES_RECEIVED",
  ACTIVITIES_RECEIVED: "ACTIVITIES_RECEIVED",
  ACTIVITY_SET_RECEIVED: "ACTIVITY_SET_RECEIVED"
};

